---
{{- if and .Values.ingress.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "charts.fullname" $ }}
  labels:
    router: {{ .Values.ingress.router }}
    {{- include "charts.labels" $ | nindent 4 }}
spec:
  host: {{ .Values.ingress.host | quote }}
  port:
    targetPort: {{ $.Values.service.port }}
  to:
    kind: Service
    name: {{ include "charts.fullname" $ }}
    weight: 100
  wildcardPolicy: None
{{- end }}