replicaCount: 1

image:
  repository: docker.dragonflydb.io/dragonflydb/dragonfly
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 6379
  protocol: TCP
  name: http

ingress:
  enabled: true
  router: private
  annotations:
    kubernetes.io/ingress.class: dragonfly
    kubernetes.io/tls-acme: "false"
  host: 'dragonfly'

resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi

autoscaling:
  enabled: false

